name: Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # veya başka bir sürüm kullanabilirsiniz

      - name: Install dependencies
        run: npm install  # package.json'dan bağımlılıkları yükler

      - name: Run bot
        run: node index.js  # botu çalıştırır
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Discord token'ı burada kullanılır
